services:
  unbound:
    image: mvance/unbound-rpi:latest
    container_name: unbound
    volumes:
      - ./unbound_config/:/opt/unbound/etc/unbound/
      - unbound_data:/opt/unbound/etc/unbound
    restart: unless-stopped
    networks:
      - pihole_network

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: Europe/Prague
      FTLCONF_dns_upstreams: unbound
      FTLCONF_dns_listeningMode: ALL
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
    volumes:
      - pihole_config:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    depends_on:
      - unbound
    restart: unless-stopped
    networks:
      - pihole_network

volumes:
  unbound_data:
  pihole_config:
  pihole_dnsmasq:

networks:
  pihole_network:
    driver: bridge