services:
  unbound:
    image: mvance/unbound-rpi:latest
    container_name: unbound
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    volumes:
      - ./unbound_config/:/opt/unbound/etc/unbound/
      - /dev:/opt/unbound/etc/unbound/dev
    restart: unless-stopped
    networks:
      dns_net:
        ipv4_address: 172.23.0.8

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: Europe/Prague
      FTLCONF_dns_upstreams: unbound
      FTLCONF_dns_listeningMode: ALL
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
    volumes:
      - pihole_config:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    depends_on:
      - unbound
    restart: unless-stopped
    networks:
      dns_net:
        ipv4_address: 172.23.0.7


volumes:
  unbound_data:
  pihole_config:
  pihole_dnsmasq:

networks:
  dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
