networks:
  dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      dns_net:
        ipv4_address: 172.23.0.7
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      # Uncomment if using Pi-hole as DHCP server
      #- "67:67/udp"
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
      FTLCONF_dns_upstreams: 'unbound'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - pihole_data:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/
    cap_add:
      # Uncomment if using DHCP
      #- NET_ADMIN
      # Optional for better priority
      - SYS_NICE
    restart: unless-stopped
    depends_on:
      - unbound

  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    networks:
      dns_net:
        ipv4_address: 172.23.0.8
    volumes:
      - ./unbound:/opt/unbound/etc/unbound
    restart: unless-stopped

volumes:
  pihole_data:
  pihole_dnsmasq: